server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    name: seckill
    url: jdbc:mysql://127.0.0.1:3306/springboot-seckill?useSSL=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
